services:
  authelia:
    container_name: authelia
    image: docker.io/authelia/authelia:latest
    restart: unless-stopped
    networks:
      - frigate
      # expose:
      # - 9091
    volumes:
      - './authelia_config:/config'
    environment:
      - TZ=Asia/Singapore
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.authelia.rule=Host(`****.kuaqe.dev`)'
      - 'traefik.http.routers.authelia.entryPoints=https'
      - 'traefik.http.routers.authelia.tls=true'
      - 'traefik.http.middlewares.authelia.forwardAuth.address=http://authelia:9091/api/authz/forward-auth'
      - 'traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Email,Remote-Name'

  redis-authelia:
    container_name: redis-authelia
    image: redis:latest
    restart: unless-stopped
    networks:
      - frigate
    # ports:
    #  - 6379:6379
    environment:
      REDIS_PASSWORD: /run/secrets/redis_password
      ALLOW_EMPTY_PASSWORD: "no"
    command: bash -c "redis-server /usr/local/etc/redis/redis.conf"
    volumes:
      - "./redis/data:/data"
      - "./redis/config:/usr/local/etc/redis"
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    secrets:
      - redis_password

  lldap:
    container_name: lldap
    image: lldap/lldap:stable
    restart: unless-stopped
    networks:
      - frigate
      - nextcloud-aio
    #ports:
    # - 17170 web ui port
    # - 3890:3890 #LDAP
    # - 6360 LDAPS
    volumes:
      - ./lldap_data:/data
    environment:
      - "UID=1000"
      - "GID=1000"
      - "TZ=Asia/Singapore"
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.lldap.rule=Host(`****.local.kuaqe.dev`)'
      - 'traefik.http.routers.lldap.entryPoints=https'
      - 'traefik.http.routers.lldap.tls=true'
      - 'traefik.http.services.lldap.loadbalancer.server.port=17170
      - 'traefik.http.routers.middlewares=authelia@docker'

secrets:
  redis_password:
    file: redis_pass.txt

networks:
  frigate:
    external: true
  nextcloud-aio:
    external: true
